### PR TITLE
Responsiveness on article segment, auth loading state for buttons 

### PR DESCRIPTION
**Pull request by weird-samuel**

### CODE REVIEW

**Review by sijirama — COMMENTED** [review]
why are the authentication onSubmit have wrong loading state sets, they call setLoading  to false and in the finally block set it to true, so it returning as true, i don't grab samu.

**Comment by weird-samuel** [comment]
The whole logic was wrong and I was lazy to rewrite it so i altered it to work based on the already provided logic

**Comment by sijirama** [comment]
> The whole logic was wrong and I was lazy to rewrite it so i altered it to work based on the already provided logic

but it has been working, did you test this properly on your machine.

**Comment by weird-samuel** [comment]
The change affects the loaders for the buttons. Dw i'll fix it

**Review by sijirama — APPROVED** [review]

**Pull request merged**
